language: python
python:
- 3.8
- 3.7
- 3.6
- pypy3
install: 
- pip install -r requirements_dev.txt
- pip install -r requirements.txt
- pip install -U tox-travis
script: tox 
after_success:
- coveralls
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: cosmicc
  password:
    secure: I9j6IyTlnZ0YWB6jEX3fFBSUxPSih75ZWrYXWS2S7fnHJeObAa87eJtaf0pzNsoA7hUDv0LDt90W5sy1mIRHp8ODRZnnSZtxRioP2ByLOqlFLxEARxjBRBde3bsbXAq+9OnUdwPfhNlJRayoGtwGyXdofIGi4qNNowap8Pf6UrHIiNV0Xsf8Xe5otpz4uuzo1qua1hbBk5CYRkJrhLdEhqw9bYlFGmQpvLZNTy8ZgUvI/peoXvPVO0PkqLiN4SInbGadyaGejNcmXCi7d+50wmhWCBl4g4mBgyHicIw6vvyYOlA6T1H78c2Am+CRSjQgnTHp6pZ75WzrIXV6/mLuenIxIk67ayFKS4fh+c1pArzPYWi0RJ1LTNz2x51Rn1If5af4EMOfWJGMgNEVT6o6K0HrzWzI6K7LORpkyZCOEU0rf8zFXzDvHVa3CLLmvaOI2BDuWeet6THwv7i2KxIETEMdsm1ZVUFAU5PTtK30v6pmb/V/Jdd4csewyJU+A+N4LO8DTtKr7+sRnMp13JNr1CtJgsDxTV1yoNizZ4QdCulFtE0vcO6MxoS5RUpNoRpxFFqPgxprtJUF1DOND9l4PMTQfGbpNkOFjiN29ZM+M2ST7cx8tV0LnjgjVQOU6+8/82UjVPyYKV8MbZr8n7zZD1OhA3OmjOJAZ8xF/WEGnq8=
  on:
    tags: true
    repo: cosmicc/rf_info
    python: 3.8
deployment:
  password:
    secure: CtmsBfzZn/V7L2Hnz112K5jjXkjkC+yEysERLeI8bvlQlzR6a+SilQ9PRo8a8nyxTiGS8uQvngLsC1ThX95QSaOc8e3sCvo6DbcHgF2sThqgIbkNcsI3/3n353XlhkPPwX3ELx8JG0usFRYZY4DnIgDJsRWiTuoYgtQDfoWthg43Ez7mruE4oPHpvQQNpG9WKH6tOFbDcPL5KgoHZ36XnrmMzlgosRLLSMuSzXptPr5r7B5j9WRBROBmoy4uLiPS8vXA6X5dAx7S9nl1FScVvnxxnKEBurz6zFAJECDCBh3EOJqDn4G/kXHyoAOvP6gsKPZ9AtlibDdzG5lFO6mTYrh8CA6X5jgkTOSc+KoJNsf6YTupmaKqWxtaYj2OJCykeC2BEI/cLMDBFHy49xTEx0z4r7uO9kbcNc3GHiFDoDQGTu4VyRunrUKfFAysZaK2kldoOmyUk4qiSSEDgHvJrnfXAjJNqdD2TFObh1roN3qA3CaBvyzTwEhzfe46XC/gq20JHol1c9GTf0JBpM5yP5f4k201VKjoY5TrRaqw/VUCzT4XgcxyhCwGivSOQYJhzqP5tnX5bpH9kpwHFBKqEPwJ48NLq+FlEy1fgFtslqBneKti92YE/J2E7wWOJBkjt5FC+jGY/nAvMb+dTYCCzXOnV592C9cD/hNM+/yj+js=
