[tox]
envlist = py310, py311, py312, py313, py314, flake8
skip_missing_interpreters = true
    
[testenv:flake8]
basepython = python
deps = flake8
commands = flake8 rf_info tools tests

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    -r{toxinidir}/requirements_dev.txt
commands =
    coverage run --source rf_info -m pytest
    coverage report
